/* kcompat_config.h.  Generated from kcompat_config.h.in by configure.  */
/*
 * Copyright 2008-2018 Cisco Systems, Inc.  All rights reserved.
 * Copyright 2007 Nuova Systems, Inc.  All rights reserved.
 *
 * This program is free software; you may redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

#ifndef _KCOMPAT_CONFIG_H_
#define _KCOMPAT_CONFIG_H_

#define VIC_HAVE_CPUMASK_SET_CPU 1

#define VIC_HAVE_IRQ_SET_AFFINITY_HINT 1

#define VIC_HAVE_NETIF_SET_XPS_QUEUE 1

#define VIC_HAVE_PCI_ENABLE_MSIX_RANGE 1

#define VIC_HAVE_FLOW_DISSECTOR_H 1

#define VIC_HAVE_FLOW_KEYS_H 0

#define VIC_HAVE_SKB_VLAN_TAG_GET 1

#define VIC_HAVE_SKB_VLAN_TAG_PRESENT 1

#define VIC_HAVE_PKT_HASH_TYPES 1

#define VIC_HAVE_SKB_GET_HASH_RAW 1

#define VIC_HAVE_SKB_SET_HASH 1

#define VIC_HAVE_NAPI_STRUCT 1

#define VIC_HAVE_NETDEV_EXTENDED 0

#define VIC_HAVE_ETHER_ADD_EQUAL 1

#define VIC_HAVE_NETIF_F_HW_VLAN_CTAG_RX 1

#define VIC_HAVE_NETIF_F_HW_VLAN_CTAG_TX 1

#define VIC_HAVE_LIST_FOR_EACH_ENTRY_SAFE_POS_ARG 0

#define VIC_HAVE_LIST_FOR_EACH_ENTRY_POS_ARG 0

#define VIC_HAVE_NAPI_GRO_FLUSH_HAS_FLUSH_OLD_ARG 1

#define VIC_HAVE_VLAN_HWACCEL_PUT_TAG_VLAN_PROTO_ARG 1

#define VIC_HAVE_ADD_VXLAN_PORT 0

#define VIC_HAVE_NET_WARN_RATELIMITED 1

#define VIC_HAVE_PCI_DMA_MAPPING_ERROR_PDEV 1

#define VIC_HAVE_SCHEDULE_TIMEOUT_UNINTERRUPTIBLE 1

#define VIC_HAVE_KZALLOC 1

#define VIC_HAVE_SKB_LINEARIZE_GFP_ARG 0

#define VIC_HAVE_NETDEV_ALLOC_SKB 1

#define VIC_HAVE_IRQRETURN_T_TYPEDEF 1

#define VIC_HAVE_INIT_WORK 1

#define VIC_HAVE_CSUM_OFFSET 1

#define VIC_HAVE_SKB_CHECKSUM_START_OFFSET 1

#define VIC_HAVE_SKB_CSUM_START 1

#define VIC_HAVE_IP_HDR 1

#define VIC_HAVE_TCP_HDR 1

#define VIC_HAVE_TCP_HDRLEN 1

#define VIC_HAVE_SKB_TRANSPORT_OFFSET 1

#define VIC_HAVE_PCI_ENABLE_DEVICE_MEM 1

#define VIC_HAVE_DEFINE_PCI_DEVICE_TABLE 0

#define VIC_HAVE_ETHTOOL_H 1

/* #undef VIC_HAVE_ETHTOOL_CMD_SPEED_SET */

#define VIC_HAVE_NETDEV_GET_TX_QUEUE 1

#define VIC_HAVE_NETIF_TX_STOP_QUEUE 1

#define VIC_HAVE_NETIF_TX_QUEUE_STOPPED 1

#define VIC_HAVE_PRINTK_H 1

#define VIC_HAVE_NETDEV_ALLOC_SKB_IP_ALIGN 1

#define VIC_HAVE_NETDEV_FOR_EACH_MC_ADDR 1

#define VIC_HAVE_NETDEV_NAME 1

#define VIC_HAVE_NETDEV_ERR 1

#define VIC_HAVE_NETIF_SET_REAL_NUM_TX_QUEUES 1

#define VIC_HAVE_NETIF_SET_REAL_NUM_RX_QUEUES 1

#define VIC_HAVE_ALLOC_ETHERDEV_MQS 1

#define VIC_HAVE_SKB_RECORD_RX_QUEUE 1

#define VIC_HAVE_SKB_FRAG_DMA_MAP 1

#define VIC_HAVE_SKB_FRAG_SIZE 1

#define SLES_VERSION 0

#define SLES_PATCHLEVEL 0

#endif /* _KCOMPAT_CONFIG_H_ */
