#!/bin/bash

## Message.Begin.
#  This file was generated by cspg releng automation
#  if this file is committed to a tree, stop and consider
#  the choices which led to this bad decision, and then
#  remove the file.  This file should be generic, not specific
#  to a given build (i.e., you should not see this comment in
#  a committed version.sh file).
## Message.End.

option="${1}"
case "$option" in
	(--full) echo 4.5.0.7-939.23 ;;
	(--version) echo 4.5.0.7 ;;
	(--build-id) echo 939.23 ;;
	(*) echo "Usage: $0 {--full|version|build-id}";exit 1;;
esac

exit 0
