#!/bin/sh
# postrm script for kmod-usnic-verbs debian package

SU=/usr/bin/sudo

${SU} /sbin/depmod -a 4.19.0+1
cp /boot/initrd.img-4.19.0+1 /boot/initrd.img-4.19.0+1.old-kmod-enic
mkinitramfs -o /boot/initrd.img-4.19.0+1 4.19.0+1
